// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaMFbXQpcEx1Um3hsL9HjkCFSdTxKLNW0',
    appId: '1:159337550316:web:51ec82eb69cf79a21c30c9',
    messagingSenderId: '159337550316',
    projectId: 'chat-33620',
    authDomain: 'chat-33620.firebaseapp.com',
    storageBucket: 'chat-33620.appspot.com',
    measurementId: 'G-V6NJNNPQPE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD91EoXStsoAQXsSK7d-dPoea9B-aHXE3k',
    appId: '1:159337550316:android:ae3411262ae4bc711c30c9',
    messagingSenderId: '159337550316',
    projectId: 'chat-33620',
    storageBucket: 'chat-33620.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfh_mpFmcAUO9Vr3N4aoK913Cwxyjh8Cw',
    appId: '1:159337550316:ios:af3be0348f5ef4011c30c9',
    messagingSenderId: '159337550316',
    projectId: 'chat-33620',
    storageBucket: 'chat-33620.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfh_mpFmcAUO9Vr3N4aoK913Cwxyjh8Cw',
    appId: '1:159337550316:ios:ca1be425c9376aa31c30c9',
    messagingSenderId: '159337550316',
    projectId: 'chat-33620',
    storageBucket: 'chat-33620.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
